server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:sqlite:data/agent.db
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      mode: always
      encoding: UTF-8
    servlet:
      multipart:
        max-file-size: 5MB
        max-request-size: 5MB

app:
  api-key: ${DEEPSEEK_API_KEY:在这里填入你的key}
  model: deepseek-chat
  base-url: https://api.deepseek.com
  db-path: data/agent.db
  access-token: xinside
  report-cron: "0 0 7 * * ?"
        # report-cron: "0 0 7 * * ?"
