CREATE TABLE IF NOT EXISTS assignments(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  title TEXT NOT NULL,
  course TEXT,
  teacher TEXT,
  content TEXT,
  due_date VARCHAR(32),
  due_time TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  source_message_id INTEGER,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS exams(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  title TEXT NOT NULL,
  course TEXT,
  teacher TEXT,
  content TEXT,
  location TEXT,
  due_date VARCHAR(32),
  due_time TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'upcoming',
  source_message_id INTEGER,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS todos(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT,
  due_date VARCHAR(32),
  due_time TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  source_message_id INTEGER,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS courses(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  title TEXT NOT NULL,
  teacher TEXT,
  location TEXT,
  weekday INTEGER,
  weeks TEXT,
  start_time TEXT,
  end_time TEXT,
  source_message_id INTEGER,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS events(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT,
  location TEXT,
  due_date VARCHAR(32),
  due_time TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'upcoming',
  source_message_id INTEGER,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS messages(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS raw_inbox(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  content TEXT NOT NULL,
  reason TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS course_overrides(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  course_id INTEGER,
  course_title TEXT,
  override_date VARCHAR(32) NOT NULL,
  kind TEXT NOT NULL,
  new_start_time TEXT,
  new_end_time TEXT,
  new_location TEXT,
  note TEXT,
  source_message_id INTEGER,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS semester(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  start_date TEXT NOT NULL,
  total_weeks INTEGER NOT NULL,
  note TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS reports(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  report_date VARCHAR(32) NOT NULL UNIQUE,
  content TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS internships(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  company TEXT NOT NULL,
  position TEXT NOT NULL,
  city TEXT,
  salary TEXT,
  deadline TEXT,
  jd TEXT,
  link TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'new',
  source_message_id INTEGER,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS profile(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  skills TEXT,
  target_role TEXT,
  target_city TEXT,
  grade TEXT,
  note TEXT,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS study_progress(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  study_date TEXT NOT NULL,
  context TEXT NOT NULL,
  source_message_id INTEGER,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);

